### ISSUE TITLE
Issues to start ReMind

### ISSUE THREAD

**Issue by edsonbittencourt** [DonTizi/ReMind#1]
Hey, friend. Congrats on the project.

I'm not sure if I'm doing something wrong, but I'm getting the following errors when trying to start. Could you help me, please?

→ ollama run nomic-embed-text
Error: embedding models do not support chat
→ ollama create recallAI
Error: open /Users/edson/ReMind/Modelfile: no such file or directory

**Comment by DonTizi** [comment]
Hey, thank you! Yes, many people have encountered this error. I know where it comes from, and I will update it today. I will also create a demo on how to set up everything smoothly soon!

**Comment by DmacMcgreg** [comment]
in your main repo: 
`touch Modelfile`
`vim Modelfile`

paste this in:
```
FROM llama3
SYSTEM """You are RecallAI, an advanced artificial memory assistant. Your primary function is to capture, index, and summarize digital activities for easy recall. You provide detailed summaries of daily activities and answer questions based on the user's digital history. Your responses should be concise, accurate, and helpful."""
```

hit escape, type :wq, hit enter
run `ollama create recallAI`

**Comment by edsonbittencourt** [comment]
Thank you @DonTizi and @DmacMcgreg.

I also had trouble installing pyaudio, which I only solved by installing portaudio via homebrew first. I'm not sure if it's a common issue, but I decided to share in case anyone else encounters the same problem.

**Comment by DonTizi** [comment]
What I would have liked is to be able to use ScreenCaptureKit with Swift to use specific codes for specific applications, for example when Zoom is open, we can start a script that captures the audio on it or ask the user if we want record this meeting. for now the record_audio.py just captures everything it hears if you activate it and I haven't included it in main.py, I'm chatting with someone on reddit who codes in Swift and who would be ready to help, it would be a good implementation!

**Comment by edsonbittencourt** [comment]
I'm the one talking to you on Reddit. I'm studying the project a bit to try to help. I made a fork and translated the README into Brazilian Portuguese in the meantime. Feel free to reach out to me.
