### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by DmacMcgreg** [DonTizi/ReMind#3]
Hey there! Excited to see this come to life, but right now it doesn't seem to work.

![CleanShot 2024-05-23 at 09 26 52@2x](https://github.com/DonTizi/ReMind/assets/3266023/c65d422f-90c1-4bd5-8fa7-3990838254d2)

**Comment by DonTizi** [comment]
**Good to know that you were able to start the application anyway.**

My explanations were brief, so let me clarify a few points:

1. **Flask Server Issue:** In the version deployed on GitHub, the `indexing.py` file has a Flask server that does not restart at a defined time. As a result, it loads the old content of the JSON file with only the sample data.

2. **Upcoming Fix:** I will deploy a new version very soon, which I've been using and has these problems fixed. 

3. **Check `main.py`:** Ensure that `main.py` is performing its job correctly. If not, please send me the error messages.

4. **Live Screen Monitoring:** The process works as follows:
   - A screenshot is taken every 2 seconds.
   - If the screen is not similar to the previous 2 seconds (using similarity algorithms), the screenshot is stored in a database.
   - These stored screenshots are then transcribed and implemented in a JSON file with the date and time.
   - The JSON file data is embedded in a vector database for indexing and querying.

5. **Action Required:** Either:
   - Restart your Flask server regularly.
   - Wait for the fix I will deploy soon, which will reload the JSON file every 5-10 minutes. Let me know which option you prefer.

**Comment by DmacMcgreg** [comment]
3. looks like there are some errors 

![CleanShot 2024-05-23 at 09 47 52@2x](https://github.com/DonTizi/ReMind/assets/3266023/c40d7fbf-357f-44d2-b895-1b6ac8d477ab)

**Comment by DonTizi** [comment]
Can you manually create a folder logs/ and a file app.log in memory_capture, and restart the main.py file? 

Sorry I deployed the old version cause I wanted to finish the new one before pushing it,

**Comment by DmacMcgreg** [comment]
Error is gone! But still same results from above. I can see some logs about storing info in the chroma db..

**Comment by DonTizi** [comment]
Can you double check the all_texts.json to see if the data is putted correctly?

**Comment by DmacMcgreg** [comment]
![CleanShot 2024-05-23 at 14 57 47@2x](https://github.com/DonTizi/ReMind/assets/3266023/8bc6d892-e254-465e-9f3d-a1c24a10db95)
![CleanShot 2024-05-23 at 14 57 58@2x](https://github.com/DonTizi/ReMind/assets/3266023/4a75a05a-84d3-4606-8262-d9fc356c9f7b)

**Comment by DonTizi** [comment]
Here is the issue: the screen recorder seems to work, but the transcription is not working well. Can you provide me with the logs of your app.log in memory-capture/logs?

**Comment by DonTizi** [comment]
I will deploy the optimal version tomorrow along with a demo. Sorry for the delay, I was quite overwhelmed today.

**Comment by DmacMcgreg** [comment]
@DonTizi The app.log seems to be over 37GB in size 🤯

**Comment by DonTizi** [comment]
Wow… delete it. I’ll add this to my to-do list. I added this log feature just for debugging to see where it didn’t work when I was coding. I’ll try to optimize it and either reduce it or delete it completely. Thanks for letting me know!

**Comment by stark1tty** [comment]
@DmacMcgreg @DonTizi I found a solution to this; or a similar issue... there is no transcriptions folder in memory_capture. The script is going to have to be modified to check for the folder and create it if it isn't there.
