### ISSUE TITLE
Getting it working on Mac

### ISSUE THREAD

**Issue by ihgalis** [DonTizi/ReMind#7]
Hi there,

I tried it today to make it runnable on a M2 Macbook. The requirements installation already failed when it came to pyaudio (Python 3.11.4)

```
ERROR: Failed building wheel for pyaudio
Failed to build pyaudio
ERROR: Could not build wheels for pyaudio, which is required to install pyproject.toml-based projects
```

How ever it worked with

`brew install pyaudio`

When it comes to ollama, the last command doesn't work. 

`ollama create reacllAI` 

just leads to "/Useres/blabla/.../Modelfile: no such file or directory"

Where was it supposed to appear? Did I miss something with Ollama?

I really feel lost :-) But I am really interested in this project.

**Comment by DmacMcgreg** [comment]
@DonTizi  check this project out:
https://github.com/openrecall/openrecall
